export const OPERATIVES = [
  { id: 'OP-01', name: 'Maria Santos' },
  { id: 'OP-02', name: "James O'Brien" },
  { id: 'OP-03', name: 'Aisha Khan' },
  { id: 'OP-04', name: 'Tomasz Nowak' },
  { id: 'OP-05', name: 'Leah Fitzgerald' },
  { id: 'OP-06', name: 'Daniel Osei' },
]

export const CLIENTS = [
  {
    id: 'CL-01',
    name: 'Northgate Retail Group',
    sector: 'Retail',
    contactName: 'Sandra Wells',
    contactEmail: 'sandra.wells@northgateretail.co.uk',
    contactPhone: '0161 555 0142',
    accountManager: 'Priya Chandra',
    contractStartDate: '2024-03-01',
    notes: 'High footfall sites, evidence turnaround is contractually 4 hours after shift end.',
  },
  {
    id: 'CL-02',
    name: 'Oakview Business Park',
    sector: 'Commercial Office',
    contactName: 'Michael Reyes',
    contactEmail: 'm.reyes@oakviewbp.com',
    contactPhone: '020 7946 0512',
    accountManager: 'Priya Chandra',
    contractStartDate: '2023-09-15',
    notes: 'Facilities team reviews reports every Monday. Very evidence-conscious client.',
  },
  {
    id: 'CL-03',
    name: 'Meridian Health Partners',
    sector: 'Healthcare',
    contactName: 'Dr. Elaine Foster',
    contactEmail: 'e.foster@meridianhealth.org',
    contactPhone: '0113 555 0198',
    accountManager: 'Owen Bradley',
    contractStartDate: '2022-11-01',
    notes: 'Infection control standards apply. Missing evidence must be flagged same day.',
  },
  {
    id: 'CL-04',
    name: 'Fairfield Learning Trust',
    sector: 'Education',
    contactName: 'Grace Malone',
    contactEmail: 'g.malone@fairfieldtrust.ac.uk',
    contactPhone: '01223 555 0176',
    accountManager: 'Owen Bradley',
    contractStartDate: '2024-01-10',
    notes: 'Cleaning must occur outside term-time hours where possible.',
  },
]

export const SITES = [
  {
    id: 'ST-01',
    name: 'Northgate Shopping Centre',
    clientId: 'CL-01',
    address: '14 Northgate High Street, Manchester',
    postcode: 'M1 4EZ',
    siteContact: 'Ben Carter',
    phone: '0161 555 0201',
    accessNotes: 'Use loading bay entrance on Cross Street. Key code: 4471#. Security must be notified 30 mins before arrival.',
    addedDate: '2024-03-05',
  },
  {
    id: 'ST-02',
    name: 'Riverside Retail Park',
    clientId: 'CL-01',
    address: '2 Riverside Way, Salford',
    postcode: 'M50 3XW',
    siteContact: 'Nina Osei',
    phone: '0161 555 0234',
    accessNotes: 'Site manager holds keys, collect from Unit 3 office 8am-6pm.',
    addedDate: '2024-04-12',
  },
  {
    id: 'ST-03',
    name: 'Oakview Tower A',
    clientId: 'CL-02',
    address: '100 Oakview Boulevard, London',
    postcode: 'EC2A 3JN',
    siteContact: 'Harriet Voss',
    phone: '020 7946 0521',
    accessNotes: 'Sign in at reception desk, level 0. Fob access required for floors 3-12, ask concierge.',
    addedDate: '2023-09-20',
  },
  {
    id: 'ST-04',
    name: 'Oakview Tower B',
    clientId: 'CL-02',
    address: '102 Oakview Boulevard, London',
    postcode: 'EC2A 3JP',
    siteContact: 'Harriet Voss',
    phone: '020 7946 0521',
    accessNotes: 'Shared reception with Tower A. Cleaning cupboard on each floor, master key from security.',
    addedDate: '2023-09-20',
  },
  {
    id: 'ST-05',
    name: 'Meridian Clinic - Central',
    clientId: 'CL-03',
    address: '45 Meridian Road, Leeds',
    postcode: 'LS1 6AB',
    siteContact: 'Dr. Elaine Foster',
    phone: '0113 555 0198',
    accessNotes: 'Clinical waste protocol applies in treatment rooms. PPE required at all times. Enter via staff entrance B.',
    addedDate: '2022-11-08',
  },
  {
    id: 'ST-06',
    name: 'Meridian Clinic - North',
    clientId: 'CL-03',
    address: '9 Northfield Avenue, Leeds',
    postcode: 'LS7 2DD',
    siteContact: 'Rajesh Patel',
    phone: '0113 555 0142',
    accessNotes: 'Smaller satellite clinic. Alarm code changes weekly, check with practice manager.',
    addedDate: '2023-02-14',
  },
  {
    id: 'ST-07',
    name: 'Fairfield Primary Academy',
    clientId: 'CL-04',
    address: '5 School Lane, Cambridge',
    postcode: 'CB2 1TN',
    siteContact: 'Grace Malone',
    phone: '01223 555 0176',
    accessNotes: 'Access only permitted after 4pm on school days. Caretaker holds spare keys, notify office by text on arrival.',
    addedDate: '2024-01-15',
  },
]

function seedPhotos(count, hex) {
  return Array.from({ length: count }, (_, i) => ({
    id: `seed-${hex}-${i}`,
    dataUrl: `https://placehold.co/400x300/${hex}/ffffff?text=Evidence+${i + 1}`,
  }))
}

export const INITIAL_JOBS = [
  {
    id: 'SP-0041',
    clientId: 'CL-01',
    siteId: 'ST-01',
    taskType: 'Daily Office Clean',
    area: 'Mall concourse & food court',
    instructions: 'Food court tables must be sanitised before 07:00 opening. Concourse floor polisher is stored in the Cross Street cupboard.',
    recurrence: 'Daily',
    scheduledTime: '2026-07-24T06:00',
    operativeId: 'OP-01',
    photosRequired: 6,
    photosSubmitted: 6,
    photos: seedPhotos(6, '10b981'),
    submittedTime: '2026-07-24T07:12',
    status: 'Completed & Evidenced',
    notes: 'All areas cleaned to standard, no issues.',
  },
  {
    id: 'SP-0042',
    clientId: 'CL-01',
    siteId: 'ST-02',
    taskType: 'Washroom Deep Clean',
    area: 'Public washrooms, Unit 3-8',
    instructions: 'Use the anti-limescale product on all taps and cisterns. Photograph each of the six washroom blocks separately.',
    recurrence: 'Weekly',
    scheduledTime: '2026-07-24T05:30',
    operativeId: 'OP-02',
    photosRequired: 6,
    photosSubmitted: 1,
    photos: seedPhotos(1, 'f59e0b'),
    submittedTime: '2026-07-24T06:50',
    status: 'Missing Evidence',
    notes: 'Only one photo uploaded, operative reported app connectivity issue.',
  },
  {
    id: 'SP-0043',
    clientId: 'CL-02',
    siteId: 'ST-03',
    taskType: 'Daily Office Clean',
    area: 'Floors 3-6 open plan',
    instructions: 'Do not move any items on desks. Empty all under-desk bins into the central chute on floor 2.',
    recurrence: 'Daily',
    scheduledTime: '2026-07-23T18:00',
    operativeId: 'OP-03',
    photosRequired: 6,
    photosSubmitted: 2,
    photos: seedPhotos(2, 'ef4444'),
    submittedTime: '2026-07-23T19:40',
    status: 'At Risk',
    notes: 'Operative left site early due to reported illness, remaining floors not covered.',
  },
  {
    id: 'SP-0044',
    clientId: 'CL-02',
    siteId: 'ST-04',
    taskType: 'Communal Area Clean',
    area: 'Reception, lifts, stairwells',
    instructions: 'Lift interiors need the stainless steel polish, not the general spray. Stairwell handrails to be wiped on all 12 floors.',
    recurrence: 'Daily',
    scheduledTime: '2026-07-24T19:00',
    operativeId: 'OP-04',
    photosRequired: 6,
    photosSubmitted: 0,
    photos: [],
    submittedTime: null,
    status: 'Incomplete',
    notes: '',
  },
  {
    id: 'SP-0045',
    clientId: 'CL-03',
    siteId: 'ST-05',
    taskType: 'Clinical Area Sanitation',
    area: 'Treatment rooms 1-4',
    instructions: 'Full PPE required. Clinical waste bins must be sealed and logged before removal. Use only the yellow-label disinfectant.',
    recurrence: 'Twice daily',
    scheduledTime: '2026-07-24T07:00',
    operativeId: 'OP-05',
    photosRequired: 6,
    photosSubmitted: 6,
    photos: seedPhotos(6, '3b82f6'),
    submittedTime: '2026-07-24T08:05',
    status: 'Awaiting Review',
    notes: 'Full evidence submitted, pending manager sign-off.',
  },
  {
    id: 'SP-0046',
    clientId: 'CL-03',
    siteId: 'ST-06',
    taskType: 'Daily Office Clean',
    area: 'Waiting room & offices',
    instructions: 'Restock waiting room hand gel and tissues from the supply cupboard. Toys in the corner box to be wiped down.',
    recurrence: 'Daily',
    scheduledTime: '2026-07-24T06:30',
    operativeId: 'OP-06',
    photosRequired: 6,
    photosSubmitted: 6,
    photos: seedPhotos(6, '10b981'),
    submittedTime: '2026-07-24T07:15',
    status: 'Completed & Evidenced',
    notes: 'Clean completed, waiting room stock replenished.',
  },
  {
    id: 'SP-0047',
    clientId: 'CL-04',
    siteId: 'ST-07',
    taskType: 'Washroom Deep Clean',
    area: 'Ground floor & Year 3-6 washrooms',
    instructions: 'Child-safe products only. Year 3-6 block is accessed through the side corridor, not the main hall.',
    recurrence: 'Weekly',
    scheduledTime: '2026-07-23T16:30',
    operativeId: 'OP-01',
    photosRequired: 6,
    photosSubmitted: 2,
    photos: seedPhotos(2, 'f59e0b'),
    submittedTime: '2026-07-23T18:10',
    status: 'Missing Evidence',
    notes: 'Two photos missing for Year 3-6 block, operative to resubmit.',
  },
  {
    id: 'SP-0048',
    clientId: 'CL-04',
    siteId: 'ST-07',
    taskType: 'Daily Office Clean',
    area: 'Staff room & admin offices',
    instructions: 'Staff room fridge to be wiped inside on Fridays only. Do not touch paperwork on the admin desks.',
    recurrence: 'Daily',
    scheduledTime: '2026-07-24T16:30',
    operativeId: 'OP-02',
    photosRequired: 6,
    photosSubmitted: 0,
    photos: [],
    submittedTime: null,
    status: 'Incomplete',
    notes: '',
  },
  {
    id: 'SP-0049',
    clientId: 'CL-01',
    siteId: 'ST-01',
    taskType: 'Window & Glass Clean',
    area: 'Main entrance glazing',
    instructions: 'Requires the extendable pole kit for the upper panes. Do not attempt in high wind — reschedule and flag instead.',
    recurrence: 'Monthly',
    scheduledTime: '2026-07-22T05:00',
    operativeId: 'OP-03',
    photosRequired: 6,
    photosSubmitted: 0,
    photos: [],
    submittedTime: null,
    status: 'At Risk',
    notes: 'Job overdue by two days, no operative check-in recorded.',
  },
  {
    id: 'SP-0050',
    clientId: 'CL-02',
    siteId: 'ST-03',
    taskType: 'Washroom Deep Clean',
    area: 'Floors 3-6 washrooms',
    instructions: 'Floor 5 washroom has a known slow drain — do not overfill sinks. Report if it worsens.',
    recurrence: 'Weekly',
    scheduledTime: '2026-07-24T18:00',
    operativeId: 'OP-04',
    photosRequired: 6,
    photosSubmitted: 0,
    photos: [],
    submittedTime: null,
    status: 'Incomplete',
    notes: '',
  },
]

export const TASK_TYPES = [
  'Daily Office Clean',
  'Washroom Deep Clean',
  'Communal Area Clean',
  'Clinical Area Sanitation',
  'Window & Glass Clean',
  'Carpet & Floor Care',
]

export const RECURRENCE_OPTIONS = ['One-off', 'Daily', 'Twice daily', 'Weekly', 'Monthly']

export const SECTORS = [
  'Commercial Office',
  'Retail',
  'Healthcare',
  'Education',
  'Industrial',
  'Hospitality',
]

export const ACCOUNT_MANAGERS = ['Priya Chandra', 'Owen Bradley', 'Sam Whitfield', 'Nadia Hussein']

export const JOB_STATUSES = [
  'Completed & Evidenced',
  'Missing Evidence',
  'At Risk',
  'Incomplete',
  'Awaiting Review',
]
